version: '3.8'

services:
  postgres:
    image: postgres:14
    env_file: "pg.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  prefect-server:
    image: prefecthq/prefect:3-latest
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: "prefect-server.env"
    command: prefect server start --no-services
    ports:
      - "127.0.0.1:4200:4200"

  prefect-services:
    image: prefecthq/prefect:3-latest
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: "prefect-service.env"
    command: prefect server services start

volumes:
  postgres_data:
  redis_data: