deployments:
  - name: 'Cybergov - PROD'
    flow_name: 'Polkadot Governance Voting'
    entrypoint: governance_flow.py:governance_flow
    work_pool:
      name: 'prod-cybergov-pool'

  - name: 'Cybergov - STAGING'
    flow_name: 'Polkadot Governance Voting'
    entrypoint: governance_flow.py:governance_flow
    work_pool:
      name: 'staging-cybergov-pool'