name: Test with Direct SSH Tunnel

on:
  # Run every day at 5:30 AM UTC
  schedule:
    - cron: '30 5 * * *'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - prod

jobs:
  cybergov:
    name: Cybergov 
    runs-on: ubuntu-latest

    env:
      ENV: ${{ github.event.inputs.environment || 'staging' }}
      PREFECT_API_URL: "http://localhost:4200"
      PREFECT_POOL_NAME: ${{ (github.event.inputs.environment || 'staging') }}-cybergov-pool

    steps:
      ## Runner setup 
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 3. Install dependencies
        run: |
          pip install -r requirements.txt

      ## Infra setup, too lazy to host a runner tbh
      - name: 4. Establish SSH Tunnel directly
        run: ./scripts/01_setup_tunnel.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: 5. Start Cybergov Worker
        run: |
          prefect worker start --pool "${PREFECT_POOL_NAME}" --run-once
        