name: 'Paseo - Cybergov Proposal Processor'

run-name: "🗳️ Process Proposal #${{ inputs.proposal_id }} on Paseo"

on:
  workflow_dispatch:
    inputs:
      proposal_id:
        description: 'The proposal ID to process'
        required: true
        type: string

jobs:
  cybergov:
    name: 'Cybergov for #${{ inputs.proposal_id }} on Paseo'
    runs-on: ubuntu-latest

    environment: Cybergov

    env:
      PROPOSAL_ID: ${{ inputs.proposal_id }}
      NETWORK: 'paseo'
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_ACCESS_KEY_SECRET: ${{ secrets.S3_ACCESS_KEY_SECRET }}
      S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 3. Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 4. Run Evaluation and Voting Script
        run: python src/cybergov_evaluate_single_proposal_and_vote.py